import pytest

def test_failure():
  assert Failure
